### PR TITLE
Fixed typo in integrations doc

### PR DESCRIPTION
**Pull request by kburger**
Minor typo: raher -> rather.

### CODE REVIEW

**Comment by MarekSuchanek** [comment]
Sorry, did not notice this earlier... Could you rebase it based on current `develop` please? (Or I can fix it directly in the develop.)

**Comment by kburger** [comment]
Should be rebased now, let me know if it wasn't done properly.

**Comment by MarekSuchanek** [comment]
Um... desired state would be to have just 1 commit diff in PR 😄 maybe the easiest way it to do it again.

**Comment by kburger** [comment]
Alright, I'll create a new PR.

**Pull request closed without merging**
